name: Videos Index Website Update

on:
  push:
    branches: [master]

jobs:
  trigger-website-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website build
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.WEBSITE_TRIGGER_DISPATCH }}" \
          https://api.github.com/repos/devilsec/website/dispatches \
          -d '{"event_type":"deployment"}'
